config/routes.rb
Treethinger::Application.routes.draw do
  devise_for :users
  root 'dynamic_pages#index'
  resources :adventures, only: [:index, :show] do
    resources :enrollments, only: [:create]
  end 
  resources :lessons, only: [:show]
  namespace :admin do
    resources :sections, only: [] do
      resources :lessons, only: [:new, :create]
    end
    resources :courses, only: [:new, :create, :show] do
        resources :sections, only: [:new, :create]      
    end
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
	mount_uploader :image, ImageUploader

	belongs_to :user
	has_many :sections

	validates :title, presence: true
	validates :description, presence: true
	validates :points, presence: true, numericality:{greater_than_or_equal_to: 0}
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	mount_uploader :video, VideoUploader
	belongs_to :section
end

app/models/section.rb
class Section < ActiveRecord::Base
	belongs_to :course
	has_many :lessons

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :courses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
	before_action :authenticate_user!
	before_action :require_authorized_for_current_course, only: [:show]
	def new 
		@course = Course.new
	end

	def create
		@course = current_user.courses.create(course_params)
		if @course.valid?
		redirect_to admin_course_path(@course)
		else
		render :new, status: :unprocessable_entity
		end
	end

	def show

	end
	private

	def require_authorized_for_current_course
		if current_course.user != current_user
			render text: "unauthorized", status: :unauthorized
		end
	end

	helper_method :current_course
	def current_course
		@current_course ||= Course.find(params[:id])
	end

	def course_params 
		params.require(:course).permit(:title, :description, :points, :image)
	end
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < ApplicationController
	before_action :authenticate_user!
	before_action :require_authorized_for_current_section
	def new
		@lesson = Lesson.new
	end

	def create 
		@lesson = current_section.lessons.create(lesson_params)
		redirect_to admin_course_path(current_section.course)
	end


	private

	def require_authorized_for_current_section
		if current_section.course.user != current_user
			return render text: "unauthorized", status: :unauthorized
		end
	end


	helper_method :current_section
	def current_section
		@section ||= Section.find(params[:section_id])
	end

	def lesson_params
			params.require(:lesson).permit(:title,:subtitle,:video)	
	end
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < ApplicationController
	before_action :authenticate_user!
	before_action :require_authorized_for_current_course
	def new 
    	@section = Section.new
	end
	
	def create 
		@section = current_course.sections.create(section_params)
		redirect_to admin_course_path(current_course)
	end

	private

	def require_authorized_for_current_course
		if current_course.user != current_user
			render text: "unauthorized", status: :unauthorized
		end
	end

	helper_method :current_course
	def current_course
		@current_course ||= Course.find(params[:course_id])
	end
	def section_params
		params.required(:section).permit(:title)
	end
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
	def index
		# we are using the Course variable from the admin controller here to list out the courses and storing them in adventures
		@adventures = Course.all
	end	

	def show
		@adventures = Course.find(params[:id])
	end

	private
		def adventure_params 
		params.require(:course).permit(:title, :description, :points, :image)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dynamic_pages_controller.rb
class DynamicPagesController < ApplicationController
	def index
		@latest_trees = Course.all.order(updated_at: :desc).limit(3)
	end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
	before_action :authenticate_user!

	def create
		current_user.enrollments.create(course: current_course)
		redirect_to adventure_path(current_course)
	end

	private 

	def current_course
		    @current_course ||= Course.find(params[:course_id])
	end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
	def show
	end

	private
	helper_method :current_lesson
	def current_lesson
		@current_lesson ||= Lesson.find(params[:id])
	end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
end

app/helpers/admin/lessons_helper.rb
module Admin::LessonsHelper
end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/admin/courses/new.html.erb
<br/>
<br/>
<br/>
	<div class="container">
	<h1>START A NEW TREE ADVENTURE </h1>
		<%= simple_form_for @course, url: admin_courses_path do |f| %>
		<div class="group">
				<%= f.input :title %>
				<span class="highlight"></span>
				<span class="bar"></span>
				<%= f.label :title %>	
		</div>
		<div class="group">
			<%= f.input :description %>
			<span class="highlight"></span>
			<span class="bar"></span>

		</div>
		<div class ="group">
			<%= f.input :points %>
			<span class="highlight"></span>
			<span class="bar"></span>
		</div>
		<div class ="group">
			<%= f.input :image %>
			<span class="highlight"></span>
			<span class="bar"></span>
		</div>
		<br/>
		<%= f.submit "Create", class: "btn btn-primary" %>
		<%end%>
		</div>

app/views/admin/courses/show.html.erb
<br/>
<br/>
<br/>
<br/>
<div class="nice-box">
	<h1 class="text-center col-xs-6">Adventure Name:</h1>
	<h1 class="text-center col-xs-6"><b><%= current_course.title %></h1></b>
	<br class="clr">
	<br class="clr">
	<h3 class="text-center col-xs-6">Points:</h3>
	<h3 class="text-center col-xs-6"><b><%= current_course.points%></b></h3>
	<br class="clr">
	<br class="clr">
	<h3 class="text-center col-xs-6">What is it about?</h3>
	<h3 class="text-center col-xs-6"><b><%= current_course.description%></b></h3>
	<br class="clr">
	<br class="clr">
		<div class ="text-center">
			<br class="clr">
			<%= link_to 'add new section', new_admin_course_section_path(current_course), class: 'btn btn-primary'%>
			<%= link_to 'preview your creation', adventure_path(current_course), class: 'btn btn-warning'%>
			<br class="clr">
		</div>
	<ul> 
		<% current_course.sections.each do |section| %>
			<li>
			 	<%= section.title %>
			 	<%= link_to 'New Lesson', new_admin_section_lesson_path(section) %>
			 	<ul>
			 		<% section.lessons.each do |lesson| %>
			 			<li>
			 				<b><%= lesson.title %></b>
			 				-
			 				<%= lesson.subtitle %>
			 			</li> 
			 		<% end %>
			 	</ul>
			 	<br class="clr">
			</li>
		<%end%>
	</ul>
<br class="clr">
</div>

app/views/admin/lessons/new.html.erb
<br/>
<br/>
<br/>
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>A new lesson</h1>
	<%= simple_form_for @lesson, url: admin_section_lessons_path(current_section) do |f| %>
		<%= f.input :title %>
		<%= f.input :subtitle %>
		<%= f.input :video %>
		<%= f.submit "add the lesson" %>
	<% end %>
</div>

app/views/admin/sections/new.html.erb
<br/>
<br/>
<br/>
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>Add a new section</h1>
 		<%= simple_form_for @section, url: admin_course_sections_path(current_course) do |f| %>
    	<%= f.input :title %>
    	<br/>
    	<%= f.submit "Add a section" %>
    	<br/>
		<br/>
  	<% end %>
</div>

app/views/adventures/index.html.erb
<br/>
<br/>
<br/>
<div class="container">
		<h1>START A NEW TREE ADVENTURE</h1>
		<% @adventures.each do |adventure| %>
	</div>	
 	<div class="col-sm-6 col-xs-12">
 		<div class="nice-box">
 		<br/>
 		<h2><%= link_to adventure.title, adventure_path(adventure) %></h2>
 		<%= image_tag adventure.image, class: 'img-responsive' %>
 		<h3><%= adventure.description%></h3>
 		<h4><%= adventure.points%></h4>
 		<br class="clr">
 	<div class ="col-xs-3 col-xs-offset-9">
 		<%= link_to 'Start Now', adventure_path(adventure), class: 'btn btn-primary' %>
		<br class="clr">
	</div>
	</div>
	<br class="clr">
	<%end%>
</div>

app/views/adventures/show.html.erb
<br/>
<br/>
<br/>
	<div class="nice-box">
		<br/>
		<h1><%= @adventures.title %></h1>
		<br/>
		<h3><%= @adventures.description%></h3>
		<br/>
		<%= image_tag @adventures.image, class: 'img-responsive' %>
 		<h4><span class="label label-success"><%= number_to_human(@adventures.points, units: {unit: "points"})%></span></h4>
		<br/>
		<%= link_to 'Enroll', adventure_enrollments_path(@adventures), class: 'btn btn-primary', method: :post %>
	</div>
	<div class="col-xs-12">
		<% @adventures.sections.each do |section| %>
		<div class = "section">
			<% section.title %>
			<% section.lessons.each do |lesson| %>
				<div class ="lesson">
					<%= link_to lesson_path(lesson) do %>
					<b><%= lesson.title %></b>
					-
					<%= lesson.subtitle %>
					<% end %>
				</div>
			<% end %>
		</div>
		<% end %>
	</div>
</div>

app/views/dynamic_pages/index.html.erb
<div class = 'hero'>
</div>
	<div class="herotext col-xs-10 col-xs-offset-1">
		<div class="h2text">
			Like that Pokemon game 
			<br /> but without the fucking Pokemon
			<br /> and for trees 
		</div>
		<%= link_to 'Play Now', new_admin_course_path, class: 'btn-lg btn-success' %>
	</div>
	<div class="row">
		<% @latest_trees.each do |tree| %>
			<div class="grid-home col-xs-10 col-xs-offset-1 col-md-offset-0 col-md-4">
					<%= tree.title %>
					<div class="center-block">
						<a class="thumbnail">
							<%= image_tag tree.image, class: 'img-responsive' %>
							<%= link_to 'Name This Tree', adventure_path(tree), class: 'btn-lg btn-success' %>
							<br/>
							<br/>
						</a>
					</div>
			</div>
		<% end %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
  <title>Name That Tree</title>

  <!-- Bootstrap -->
  <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> -->
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <link href="http://vjs.zencdn.net/5.0.2/video-js.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/5.0.2/video.js"></script>

</head>
<body>
  <div id="wrap">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Name That Tree!</a>
         <!-- <img alt="Brand" src ="tree2.jpeg" -->
        </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a <%= link_to '+Add Tree', new_admin_course_path %> </a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <%if user_signed_in? %>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <%else %>
              <li><%= link_to 'Log In', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <%end%>
           </ul><!-- navbar right -->  
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
      <% if notice.present? %>
         <p class="text-center alert alert-success"><%= notice %></p>
      <% end %> 
      <% if alert.present? %>
         <p class="text-center alert alert-warning"><%= alert %></p>
      <% end %>
    <%= yield %>  
  </div> <!-- wrap -->
  <br class="clr" />
    <div id = "footer">
    <div class="container-fluid">
        <div class ="col-xs-3"> <%= link_to 'Some Tree Stuff', '#' %> </div>
        <div class ="col-xs-3"><%= link_to 'Tree Experts', new_admin_course_path %></div>
        <div class ="col-xs-3"><%= link_to 'Tree Adventures', adventures_path %></div>
    </div>
  </div>
    <!-- jQuery 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!- Bootstrap JavaScript -->
    <!--<script src="js/bootstrap.min.js"></script>-->
</body>
</html>

app/views/lessons/show.html.erb
<br/>
<br/>
<br/>
	<div class="nice-box">
		<br/>
		<h1><%= current_lesson.title %></h1>
		<br/>
		<h3><%= current_lesson.subtitle %></h3>
		<br/>
		 <video id="my-video" class="video-js vjs-default-skin vjs-big-play-centered vjs-fluid" width="200"height="100" controls preload="auto" poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
  	  		<source src="<%= current_lesson.video.to_s %>" type='video/mp4'>	
 	   			<p class="vjs-no-js">
    				To view this video please enable JavaScript, and consider upgradiny to a web browser that 
      				<a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    			</p>
  		</video>
		<%= link_to 'Video', current_lesson.video.to_s %>		 
	</div>
<br/>